version: "3.9"

networks:
  music-management-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:

services:

  postgres:
    image: postgres:16-alpine
    container_name: music-management-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - music-management-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ./apimusicmanagement
      dockerfile: Dockerfile
    container_name: api-music-management
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE_ACTIVE}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${API_PORT}:8083"
    networks:
      - music-management-network

  minio:
    image: minio/minio:latest
    container_name: music-management-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data
    networks:
      - music-management-network

  minio-init:
    image: minio/mc:latest
    container_name: music-management-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
        echo 'Aguardando MinIO...';
        sleep 2;
      done;
      mc mb -p local/album-images || true;
      echo 'Bucket album-images ok';
      mc mb -p local/artist-images || true;
      echo 'Bucket artist-images ok';
      "
    networks:
      - music-management-network
  
  music-management-frontend:
    build:
      context: ./musicManagement
      dockerfile: Dockerfile
    container_name: music-management-frontend
    restart: unless-stopped
    depends_on:
      - api
      - minio
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - music-management-network
